### ISSUE TITLE
can't find dataset

### ISSUE THREAD

**Issue by ChloeKiwi** [caio-freitas/GraphARM#5]
Hi! Thank's for your wonderful work! 
I want to reproduce this coder for research, but I can't find the dataset you mentioned in the paper. Can you provide some of the dataset you used?
Thank you!

**Comment by caio-freitas** [comment]
Hi @ChloeKiwi, sure!

I've used the ZINC dataset from `pytorch_geometric` (`torch_geometric.datasets.ZINC`). It's actually downloaded by the script `train.py`, if you don't already have it locally on your machine (in [this line](https://github.com/caio-freitas/GraphARM/blob/f97ef5c292f94d6a34418ab9d4f3aa5ce2dfd303/train.py#L17))
