### ISSUE TITLE
Generate new graphs

### ISSUE THREAD

**Issue by shivang-22** [caio-freitas/GraphARM#6]
Hello, thank you for the implementation. Could you direct me to the code that, once a model is trained, can generate new molecular graphs?

**Comment by caio-freitas** [comment]
Hello @shivang-22! Once the model is trained, a new molecular graph can be generated by creating an empty graph (a single masked node, connected to itself by a masked edge) and iteratively adding nodes using the results from the [predict_new_node](https://github.com/caio-freitas/GraphARM/blob/f97ef5c292f94d6a34418ab9d4f3aa5ce2dfd303/grapharm.py#L224) function.

**Comment by shivang-22** [comment]
Hello @caio-freitas , thank you for pointing me in the right direction. I just wanted a follow-up clarification. When I train a toy model (with obviously high errors) just to play around with the code, the first time when I call `predict_new_node` gives me `new_connections = tensor([2,2])`. I wanted clarification on whether this edge attribute can be a vector or not. Could you elaborate on this? Additionally, from my understanding, there is no information on which existing nodes will the newly predicted node be connected to. Is that correct or have I missed something?

**Comment by caio-freitas** [comment]
- In theory, the edge attributes could be a vector. But the edges need to be sampled from a categorical distribution, so I think for this method (that predicts categorical node and edge features) it makes sense to use an enumerable type.
- About the predicted connections, the newly predicted node will be connected to all nodes (the type of this edges is the only thing to be inferred). The inferred connections are also retuned by the `predict_new_node()` method.
