### ISSUE TITLE
About the timing and GPU specs in Table 2

### ISSUE THREAD

**Issue by veghen** [caio-freitas/GraphARM#7]
Hi, thank you for this incredible work! I have two quick questions about Table 2:

1. Does the reported time refer to one molecule or the whole test set?
2. Could you kindly share the information about the GPU device used for running the experiments in Table 2?

Thank you so much for your time and for sharing this great research!

**Comment by caio-freitas** [comment]
Hello @veghen, I would not know for sure, since I have just developed this implementation and not written the original paper. But it does seem like it refers to the whole test set. About their hardware setup (e.g. GPU devices), I also have not found it in the paper.
